spring:
  # 1. 禁用 MySQL/MyBatis 相关自动配置
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
  data:
    mongodb:
      uri: mongodb://root:123456@mongodb:27017/test?authSource=admin&maxPoolSize=20&waitQueueTimeoutMS=2000

app:
  datasource: mongo
